apiVersion: 1

datasources:
  # Primary Prometheus datasource for Docker Compose
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus_server:9090 # Docker Compose service name
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}
    
  # Prometheus datasource for Kubernetes deployment
  - name: Prometheus-K8s
    type: prometheus
    access: proxy
    url: http://prometheus-service.ml-deployment.svc.cluster.local:9090 # Kubernetes service name
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
      # Custom headers for Kubernetes authentication if needed
      # customQueryParameters: ""
    secureJsonData: {}
    # Optional: Basic auth or token auth for Kubernetes
    # basicAuth: false
    # basicAuthUser: ""
    # withCredentials: false
    
  # Alternative Prometheus datasource using environment variable
  - name: Prometheus-Env
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL:http://prometheus_server:9090}
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}
