apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-config
  namespace: ml-deployment
data:
  POSTGRES_DB: "mlflow"
  POSTGRES_PORT: "2345"
  MINIO_PORT: "9000"
  MINIO_CONSOLE_PORT: "9001"
  MLFLOW_PORT: "5001"
  FASTAPI_PORT: "8000"
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3000"
  MODEL_NAME: "iris-classifier"
  MODEL_STAGE: "production"
