apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ml-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:9.5.3
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: ml-secrets
              key: GRAFANA_ADMIN_USER
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ml-secrets
              key: GRAFANA_ADMIN_PASSWORD
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboard-files
          mountPath: /etc/grafana/provisioning/dashboards/dashboards
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards
      - name: grafana-dashboard-files
        configMap:
          name: grafana-dashboard-files
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: ml-deployment
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: ml-deployment
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: ml-deployment
data:
  dashboard.yml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /etc/grafana/provisioning/dashboards/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-files
  namespace: ml-deployment
data:
  ml-api-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "ML API Dashboard",
        "tags": ["ml", "api"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Total Predictions",
            "type": "stat",
            "targets": [
              {
                "expr": "ml_predictions_total",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "displayMode": "auto"
                }
              }
            }
          },
          {
            "id": 2,
            "title": "Model Accuracy",
            "type": "stat",
            "targets": [
              {
                "expr": "ml_model_accuracy",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percentunit",
                "color": {
                  "mode": "palette-classic"
                }
              }
            }
          },
          {
            "id": 3,
            "title": "Prediction Confidence Distribution",
            "type": "histogram",
            "targets": [
              {
                "expr": "rate(ml_prediction_confidence_bucket[5m])",
                "refId": "A"
              }
            ]
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "5s"
      }
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: ml-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi 