apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-deployment

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- postgres-deployment.yaml
- minio-deployment.yaml
- mlflow-deployment.yaml
- fastapi-deployment.yaml
- prometheus-deployment.yaml
- grafana-deployment.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: ml-deployment
  app.kubernetes.io/version: v1.0.0 