apiVersion: v1
kind: Secret
metadata:
  name: ml-secrets
  namespace: ml-deployment
type: Opaque
data:
  # Template
  # Base64 encoded values - you should replace these with your actual values
  POSTGRES_USER: bWxmbG93dXNlcg==  # mlflowuser
  POSTGRES_PASSWORD: bWxmbG93cGFzc3dvcmQ=  # mlflowpassword
  MINIO_ROOT_USER: bWluaW9hZG1pbg==  # minioadmin
  MINIO_ROOT_PASSWORD: bWluaW9hZG1pbg==  # minioadmin
  GRAFANA_ADMIN_USER: YWRtaW4=  # admin
  GRAFANA_ADMIN_PASSWORD: YWRtaW4=  # admin 