apiVersion: v1
kind: Secret
metadata:
  name: ml-secrets
  namespace: ml-deployment
type: Opaque
data:
  POSTGRES_USER: bWxmbG93
  POSTGRES_PASSWORD: bWxmbG93
  MINIO_ROOT_USER: bWluaW9hZG1pbnRlYW0xMA==
  MINIO_ROOT_PASSWORD: bWluaW9hZG1pbnRlYW0xMA==
  GRAFANA_ADMIN_USER: YWRtaW4=
  GRAFANA_ADMIN_PASSWORD: YWRtaW4=
